
services:
  redirect-redis:
    image: redis
    container_name: redirect-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  redirect-rabbitmq:
    image: rabbitmq:3-management
    container_name: redirect-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"


  analytics:
    image: bhagya888/analytics-worker
    container_name: analytics
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - redirect-rabbitmq
      - redirect-redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AMQP_URL=${AMQP_URL}
      - NEWRELIC_LICENSE=${NEWRELIC_LICENSE_2}

  redirect:
    image: bhagya888/redirect
    container_name: redirect
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - redirect-redis
      - redirect-rabbitmq
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - CURRENT_URL=${CURRENT_URL}
      - REDIS_URL=${REDIS_URL}
      - AMQP_URL=${AMQP_URL}
      - NEWRELIC_LICENSE=${NEWRELIC_LICENSE}

  